package cn.com.bsoft;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-08-26T13:31:23.807+08:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "BSXmlWsEntryClassService",
                  wsdlLocation = "http://172.16.80.168:8089/webserviceEntry?wsdl",
                  targetNamespace = "http://www.bsoft.com.cn")
public class BSXmlWsEntryClassService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.bsoft.com.cn", "BSXmlWsEntryClassService");
    public final static QName BSXmlWsEntryClassServicePort = new QName("http://www.bsoft.com.cn", "BSXmlWsEntryClassServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.16.80.168:8089/webserviceEntry?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BSXmlWsEntryClassService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://172.16.80.168:8089/webserviceEntry?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BSXmlWsEntryClassService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BSXmlWsEntryClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BSXmlWsEntryClassService() {
        super(WSDL_LOCATION, SERVICE);
    }





    /**
     *
     * @return
     *     returns BSXmlWsEntryClassServicePortType
     */
    @WebEndpoint(name = "BSXmlWsEntryClassServicePort")
    public BSXmlWsEntryClassServicePortType getBSXmlWsEntryClassServicePort() {
        return super.getPort(BSXmlWsEntryClassServicePort, BSXmlWsEntryClassServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BSXmlWsEntryClassServicePortType
     */
    @WebEndpoint(name = "BSXmlWsEntryClassServicePort")
    public BSXmlWsEntryClassServicePortType getBSXmlWsEntryClassServicePort(WebServiceFeature... features) {
        return super.getPort(BSXmlWsEntryClassServicePort, BSXmlWsEntryClassServicePortType.class, features);
    }

}
