
package cn.com.bsoft;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-08-26T13:31:23.762+08:00
 * Generated source version: 3.2.5
 *
 */
public final class BSXmlWsEntryClassServicePortType_BSXmlWsEntryClassServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.bsoft.com.cn", "BSXmlWsEntryClassService");

    private BSXmlWsEntryClassServicePortType_BSXmlWsEntryClassServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BSXmlWsEntryClassService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BSXmlWsEntryClassService ss = new BSXmlWsEntryClassService(wsdlURL, SERVICE_NAME);
        BSXmlWsEntryClassServicePortType port = ss.getBSXmlWsEntryClassServicePort();

        {
        System.out.println("Invoking invoke...");
        cn.com.bsoft.InvokeRequest _invoke_parameters = null;
        cn.com.bsoft.InvokeResponse _invoke__return = port.invoke(_invoke_parameters);
        System.out.println("invoke.result=" + _invoke__return);


        }

        System.exit(0);
    }

}
